baseURL      = 'https://jetlagguy.com.au/'
title        = 'Dr Steve Jasper'
languageCode = 'en-au'
theme        = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]

DefaultContentLanguage = "en"
contentDir             = "content/en"
SectionPagesMenu       = "main"
pagination.pagerSize   = 9
# googleAnalytics        = ""
enableRobotsTXT     = false
enableEmoji         = true
cleanDestinationDir = true
copyright           = "Dr Steve Jasper"
enableGitInfo       = true

[fonts]
    use_google_fonts      = true
    google_fonts_url      = "https://fonts.googleapis.com/css2?family=Overpass+Mono:wght@300..700&family=Overpass:ital,wght@0,100..900;1,100..900&display=swap"
    use_self_hosted_fonts = false
    logo                  = "Overpass"
    heading               = "Overpass"
    base                  = "Overpass"
    monospace             = "Overpass Mono"
