author                 = "Dr Steve Jasper"
description            = "The Jet Lag Guy"
favicon                = "/images/blueclock.png"
site_logo              
date_format            = ":date_full"
custom_css             = ["tjlg.scss"]
omit_header_text       = true
text_color             = "charcoal"               # "charcoal", or "dark-gray"
recent_posts_number    = 3
background_color_class = "bg-maroon"
body_classes           = "overpass bg-near-white"
post_content_classes   = "overpass"

# * See https://github.com/theNewDynamic/gohugo-theme-ananke/wiki/Social-media-network-setup#configure-social-media-follow-links for a list of available networks.

[ananke.social.follow]
    new_window_icon = true
    networks        = ["linkedin", "youtube", "facebook", "x-twitter", "rss"]

[ananke.social.share]
    icons     = true
    sharetext = true
    networks  = ["linkedin", "facebook", "x-twitter", "bluesky", "email"]

[ananke.social.email]
    profilelink = "mailto:drsteve@jetlagguy.com.au"

[ananke.social.linkedin]
    username = "jasperstephen"

[ananke.social.youtube]
    profilelink = "https://www.youtube.com/@TheJetLagGuy"

[ananke.social.facebook]
    profilelink = "https://www.facebook.com/steve.jasper.965/"

[ananke.social.x-twitter]
    profilelink = "https://x.com/DrSteveJasper/"


    # tiktok

    # instagram?

[ananke.social.rss]
    profilelink = "/index.xml"
