---
title: "Keynotes"
description: |
  Keynote presentations for frequent flyers and the organisations that depend on them
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Let me take you on a journey – three journeys, to be precise – in my quest to discover the causes and solutions jet lag. I'm passionate about transforming the face of international travel, so that no one has to be debilitated by jet lag ever again.

Understand the science of jet lag in a fun way, and take away some useful strategies for dealing with jet lag, for you and your whole team. Eliminate downtime and be present for your family when you return from international travel!

<aside>Dr Steve is a leading expert on jet lag from every angle: pharmacology, health science, peak performance, and organisational development.</aside>  


### Business Travellers

If you travel internationally frequently across multiple time zones, this keynote is something you’ll get value from. Learn a few simple tips and tricks from Dr Steve to maintain peak performance when you travel internationally – even if you have to fly economy!

Make your international travel easy and no-fuss, so that you’re at your mental and physical peak wherever and when you travel, even at short or no notice at all.



### Executive Assistants

For the busy EA for a frequent flyer, this is a keynote you’ll get value from. Learn the simple strategies that you can use to assist your executives as they jet around the globe, and plan their activities to minimise the impact of jet lag.

You’ll learn the tips and tricks for minimising jet lag, and enable your executives to travel the world with ease and comfort.



### Human Resources

If you’re a human resources professional looking after a team of internationally travelling staff, you need to hear how best to support your staff. This keynote will enable you to start to develop policies around international travel for staff.

Ensure that your company’s duty of care towards its employees is fulfilled, and reduce turnover and burnout in your staff with some simple, low-cost strategies.

<aside>The direction of travel, medication, and circadian rhythms are all affecting you, your team, and your bottom line. For practical strategies, there's no better choice for your next [keynote](keynotes.html) or [in-house training](workshops.html).</aside>


# Keynote Topics

Dr Steve's keynotes are tailored to your specific audience and needs. The first step is a briefing call to clarify the precise problems and solutions that would be of most benefit to your organisation or audience. Each keynote tailors the following practical strategies from jet lag science to your group's specific needs: 

### Prepare beforehand
You’ll know what you need to do to prepare yourself for a long-haul flight – what to eat, when to eat, when to sleep so that you’re ready to arrive refreshed and alert when you arrive at your destination! You’ll also learn the sneaky little trick to beating jet lag that airlines won’t tell you.

### Three Strategies
Learn the three things you need to know to minimise the impact of jet lag – three simple hacks that will transform your travel experience. You’ll learn my secret weapon that I used when I travelled to Paris that enabled me to present my work to an international audience.

### Returning home
After your long-haul flight, you want to return still performing at your peak, not falling in a heap. Learn the tactics you can use to not only manage yourself when you travel, but just as importantly, when you return home so that you’re not drained of energy, and you’re ready to participate in family, work and social life.

<br>

## Contact me
### Book Dr Steve to speak at your next event

<aside>
Based in Melbourne, Australia.
Available to speak and consult globally.
</aside>

Phone: +61 (0) 410 479 974

Email: [bookings@jetlagguy.com.au](mailto:bookings@jetlagguy.com.au)



