---
title: "Re-Timer Glasses"
description: |
  Re-Timer Glasses to help adjust your body clock
---

The [Re-Timer glasses](https://shareasale.com/r.cfm?b=2448501&u=4137385&m=148943&urllink=&afftrack=) are a fantastic tool to alleviate jet lag, and I thoroughly recommend them. Basically, these shine blue-green lights into your eyes to keep you awake, in lieu of sunlight. This can be useful before you travel – say you’re flying to London from Sydney, and it’s nighttime in Sydney but daylight in London, and you want to ease your body into London time. The other use is for when it is winter at your destination, and there simply isn’t enough sunlight during the daytime to reset your body clock.

Our eyes have special receptors that let us know when it is daytime and when it is night, and the frequency of the light in the Re-timer glasses is matches the sensitivity of the receptors. Best of all, there’s no harmful ultraviolet or deep blue light, both of which can damage the retina of the eye.

These glasses are terrific for resetting your body clock, and it’s a natural, safe, and drug-free method to avoid jet lag. Get yours [here](https://shareasale.com/r.cfm?b=2448501&u=4137385&m=148943&urllink=&afftrack=).
