---
title: "Work with me"
description: "Keynote Speaker and Consultant, *Dr Steve, The Jet Lag Guy*"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### I help international business travellers and frequent flyers understand and eliminate jet lag, and strategically improve their mental, physical, and business performance.
<aside>
Jump direclty to [keynotes](keynotes.html), [in-house workshops](workshops.html), or [strategic consulting](consulting.html)</aside>

Whether you travel for business or pleasure, you’ve likely experienced jet lag. For the millions of people who fly trans-continental or internationally each year, jet lag can be painfully real.

As a specialist consultant and speaker with a PhD in jet lag and executive performance, Dr Stephen Jasper is at the forefront of the latest technology and science in the management of jet lag.



## Why jet lag matters

The science of effectively managing jet lag can improve personal performance, relationships and the company’s bottom line.

Jet lag not only affects the person flying, but also affects their team and loved ones back home. Frequent business travel is a scientifically-proven factor in stress, weight gain, cognitive and physical performance, and has even been shown to lead to increased rates of spousal stress and divorce.

Managing jet lag is potentially one of the most valuable untapped areas of preventative intervention for business performance and wellbeing.



## 6 years researching jet lag
<aside>
29 years in biotech, an MBA, and a PhD in jet lag and executive performance.  </aside>
A qualified pharmacist with an understanding of human biology and international management, Dr Steve has dedicated himself to researching jet Lag. He has developed practical tools and individually tailored strategies to and improve individual jet lag recovery and reduce its negative physical, mental and economic impacts on performance.

A sessional lecturer at RMIT, Dr Steve holds a Bachelor of Pharmacy from the University of Sydney, an MBA and PhD from RMIT University. He speaks several languages and studied European Union studies at Århus University, Denmark. Dr Steve has worked internationally in pharmaceutical roles with companies such as CSL, Sigma Pharmaceuticals, GSK, Bristol-Myers Squibb and Swisse.



## My Methods
<aside>I speak 4 languages and have a deep passion for jet lag research and recovery in business, sport, health and relationships.
</aside>

By introducing you to the science of managing jet lag, I will demystify hidden aspects of chronobiology and performance management, and help your team to implement strategies that prevent jet lag and eliminate the negative impact on your people, profits, and performance.

In [keynote presentations](keynotes.html), [in-house workshops](workshops.html), and [strategic consulting engagements](consulting.html), I help your organisation to reduce the hidden effects of jet lag and improve your team’s performance. Drawing on the latest research by academics around the world, I present strategies to mitigate the effects of jet lag that can be tailored to each individual’s own body clock, or chronotype. You’ll walk out of the session equipped to perform at your best wherever you go, no matter how much international travel you do!

Learn how my approach and services can help improve your team's performance...

### [Keynote Presentations](keynotes.html)  ::  [In-House Workshops](workshops.html)  ::  [Strategic Consulting](consulting.html)


## Contact me
### Book Dr Steve to speak at your next event

<aside>
Based in Melbourne, Australia.
Available to speak and consult globally.
</aside>

Phone: +61 (0) 410 479 974

Email: [bookings@jetlagguy.com.au](mailto:bookings@jetlagguy.com.au)




